# Generated by Django 3.1.7 on 2021-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=100)),
                ('upload_date', models.DateField()),
                ('processed_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
    ]
