# Generated by Django 3.1.7 on 2021-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed_date',
            field=models.DateField(null=True),
        ),
    ]
